### ISSUE TITLE
Unable to access MinIO UI due to port redirection when using Docker

### ISSUE THREAD

**Issue by kringz** [jefflester/minitrino#39]
Accessing `localhost:9000` redirects to something like `localhost:34030` with a "request failed" message in the browser in the following config:

```
 minio:
    image: minio/minio
    container_name: minio
    ports:
      - '9000:9000'
    volumes:
      - './resources/minio/data/:/data'
    environment:
      MINIO_ACCESS_KEY: ${S3_ACCESS_KEY}
      MINIO_SECRET_KEY: ${S3_SECRET_KEY}
    command: server /data
```

I was able to work around this issue by adding `9001:9001` to the list of exposed ports and  'specifying `--address ":9000"` and `--console-address ":9001"` in the command parameter:

```
 minio:
    image: minio/minio
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - './resources/minio/data/:/data'
    environment:
      MINIO_ACCESS_KEY: ${S3_ACCESS_KEY}
      MINIO_SECRET_KEY: ${S3_SECRET_KEY}
    command: server --address ":9000" --console-address ":9001" /data
```
